### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by ahkhanjani** [hipstersmoothie/next-app-theme#2]
Two days of wasted time over a dark mode; trying to find a `next-themes` replacement; finally finding that GitHub thread. I'm really happy that someone took on the burden and made a package!
After the pain and suffering I went through, I cannot help but be skeptical of everything. So I'm wondering if this has solved all of the issues with Next.js. Does it work with both routers? Does it flash like `next-themes`? Can we possibly use user's system theme with this? Etc. Sorry I got too excited 😅 Thank you in advance.

If this solution actually works I'm willing to contribute to it. Please let me know if you also want to maintain this package.
Best regards.

**Comment by hipstersmoothie** [comment]
Here is it working on my own repo

https://github.com/search?q=repo%3Ahipstersmoothie%2Fhipstersmoothie.com-2%20next-app-theme&type=code

https://www.hipstersmoothie.com/

I can only attest to it working in the app router. I haven't tried on pages. If you want to contribute that i'm happy to merge
